# Generated by Django 2.2.10 on 2021-02-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face2', '0002_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='user_id',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
