# Generated by Django 2.2.10 on 2021-03-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageToText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/')),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'imagetotext',
                'verbose_name_plural': 'imagetotexts',
            },
        ),
    ]
