# Generated by Django 2.2.10 on 2021-03-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_auto_20210302_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetotext',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
